### ISSUE TITLE
MacOS compilation failed

### ISSUE THREAD

**Issue by ccccbjcn** [Berzeck/Nulstar#10]
Hi @Berzeck,
I compiled Nulstar on MacOS, there was an error for line https://github.com/Berzeck/Nulstar/blob/a9ce3b06943c3d14dda32f9490ac68f5cca75191/Libraries/Nulstar/NTools/NSignalWatcher.cpp#L101.
    __::sigemptyset(&sigact.sa_mask);_  expected unqualified-id_ 
I removed "::" that means this line code is "sigemptyset(&sigact.sa_mask);" and compiled successfully. It seams this is a namespace issue on MacOS for MACRO "sigemptyset". 
Could you change this line code and check whether compilation is fine on Linux OS?
If compilation is success, I could submit this change.
Thanks.

**Comment by Berzeck** [comment]
Hi   @ccccbjcn !

NSignalWatcher goal is to catch a close signal from the operating system so it has the opportunity to call destructors properly, I assume you are compiling including last commits; please check that with your proposed change, when killing Nulstar main process, using kill <PID> command, it also closes all remaining procesess.

**Comment by ccccbjcn** [comment]
@Berzeck Could you compile successfully on Linux OS for this change? I will test on MacOS for the killing process.

**Comment by ccccbjcn** [comment]
@Berzeck I tested it worked fine. Could you compile the change and test on linux OS? Thanks.

server-ci:debug ray$ LD_LIBRARY_PATH=Libraries/CPP/Nulstar/0.1.0:Libraries/CPP/Qt/5.12.3 Modules/Nulstar/Nulstar/0.1.0/Nulstar &
server-ci:debug ray$ ps -ef | grep Nulstar
  502   665   514   0  2:38下午 ttys000    0:00.40 Modules/Nulstar/Nulstar/0.1.0/Nulstar
  502   666   665   0  2:38下午 ttys000    0:00.40 /Users/ray/Nulstar/build-Nulstar-Desktop_Qt_5_12_1_clang_64bit-Debug/debug/Modules/Nulstar/ServiceManager/0.1.0/ServiceManager --allowednetworks 127.0.0.1/32 --commport 7771 --ip 127.0.0.1 --loglevel 4 --sslmode 0
  502   667   665   0  2:38下午 ttys000    0:00.41 /Users/ray/Nulstar/build-Nulstar-Desktop_Qt_5_12_1_clang_64bit-Debug/debug/Modules/Nulstar/Connector/0.1.0/Connector --adminport 7791 --allowednetworks 127.0.0.1/32 --clientport 7790 --commport 7772 --ip 127.0.0.1 --loglevel 4 --sslmode 0 --managerurl ws://127.0.0.1:7771
  502   669   665   0  2:38下午 ttys000    0:00.40 /Users/ray/Nulstar/build-Nulstar-Desktop_Qt_5_12_1_clang_64bit-Debug/debug/Modules/Nulstar/Updater/0.1.0/Updater --allowednetworks 127.0.0.1/32 --commport 7774 --ip 127.0.0.1 --loglevel 4 --sslmode 0 --managerurl ws://127.0.0.1:7771
  502   671   514   0  2:38下午 ttys000    0:00.00 grep Nulstar
server-ci:debug ray$ 
server-ci:debug ray$ 
server-ci:debug ray$ kill 665
Caught signal: Terminated: 15
Module 'Connector' and version '0.1.0' is not stoped by scirpt!
Closing module 'Connector'.
Module 'ServiceManager' and version '0.1.0' is not stoped by scirpt!
Closing module 'ServiceManager'.
Module 'Updater' and version '0.1.0' is not stoped by scirpt!
server-ci:debug ray$ Closing module 'Updater'.

[1]+  Done                    DYLD_LIBRARY_PATH=Libraries/CPP/Nulstar/0.1.0:Libraries/CPP/Qt/5.12.3 Modules/Nulstar/Nulstar/0.1.0/Nulstar
server-ci:debug ray$ ps -ef | grep Nulstar
  502   693   514   0  2:39下午 ttys000    0:00.00 grep Nulstar

///////git diff for this change
server-ci:Nulstar ray$ git diff
diff --git a/Libraries/Nulstar/NTools/NSignalWatcher.cpp b/Libraries/Nulstar/NTools/NSignalWatcher.cpp
index b32bd91..276b91d 100644
--- a/Libraries/Nulstar/NTools/NSignalWatcher.cpp
+++ b/Libraries/Nulstar/NTools/NSignalWatcher.cpp
@@ -98,7 +98,7 @@ void NSignalWatcherPrivate::watchForSignal(int signal)
     struct sigaction sigact;
     sigact.sa_handler = NSignalWatcherPrivate::signalHandler;
     sigact.sa_flags = 0;
-    ::sigemptyset(&sigact.sa_mask);
+    sigemptyset(&sigact.sa_mask);
     sigact.sa_flags |= SA_RESTART;
     if (::sigaction(signal, &sigact, NULL)) {
         qDebug() << "NSignalWatcher: sigaction: " << ::strerror(errno);

**Comment by Berzeck** [comment]
@ccccbjcn 
All good! Commit sent.
